xpos314.web/xpos314.web/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryTryController : Controller
    {
        private readonly XPOS_314Context db;
        private readonly CategoryTryServices categoryTryServices;

        public CategoryTryController(XPOS_314Context _db)
        {
            this.db = _db;
            this.categoryTryServices = new CategoryTryServices(db);
        }
        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryTryServices.GetAllData();
            return View(dataView);
        }

        public IActionResult Create()
        {
            VMTblCategory dataView = new VMTblCategory();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if(ModelState.IsValid)
            {
                respon = categoryTryServices.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryTryServices.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();
            if(ModelState.IsValid)
            {
                respon = categoryTryServices.Edit(dataView);
                if(respon.Success)
                    return RedirectToAction("Index");
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryTryServices.GetById(id);
            return View(dataView);
        }

        public IActionResult Delete(int id)
        {
            VMTblCategory dataView = categoryTryServices.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView)
        {
            VMResponse respon = categoryTryServices.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return View(respon.Entity);
        }
    }
}

xpos314.web/xpos314.web/Views/CategoryTry/Create.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "CREATE CATEGORY";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title" >@ViewData["Title"]</h3>
        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-2 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description">
                </div>
            </div>

            <div class="modal-footer">
                <div class="col-sm-12">
                    <a class="btn btn-outline-secondary btn-rounded" asp-controller="CategoryTry" asp-action="Index">Back to List</a>
                    <button type="submit" style="float:right" class="btn btn-primary btn-rounded">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $("#form_input").validate({
        errorClass:"text-danger",
        rules:{
            NameCategory:"required"
        },
        messages:{
            NameCategory:"Please enter Name Category"
        }        
    })
</script>

xpos314.web/xpos314.web/Views/CategoryTry/Delete.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "DELETE CATEGORY";
}

<div class="card">
    <div class="card-body">

        <form asp-action="Delete" method="post">
            <input type="hidden" name="Id" value="@Model.Id"/>

            <h3>Are you sure for delete @Model.NameCategory?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary btn-rounded">Delete</button>
                <a asp-action="Index" class="btn btn-outline-secondary btn-rounded">Back to List</a>
            </div>
        </form>

    </div>
</div>

xpos314.web/xpos314.web/Views/CategoryTry/Detail.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "DETAIL CATEGORY";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title font-weight-bold mr-2">@ViewData["Title"]</h3>
        <input type="hidden" id="Id" name="Id" value="@Model.Id" />
        <div class="mb-4 row">
            <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
            </div>
        </div>
        <div class="mb-4 row">
            <label for="Description" class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
            </div>
        </div>

    </div>
</div>

xpos314.web/xpos314.web/Views/CategoryTry/Edit.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "EDIT CATEGORY";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title font-weight-bold mr-2 mt-2">@ViewData["Title"]</h3>
        <form asp-action="Edit" method="post">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <span class="text-danger" asp-validation-for="NameCategory"></span>
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-12">
                    <a class="btn btn-outline-secondary btn-rounded" asp-controller="CategoryTry" asp-action="Index" >Back to List</a>
                    <button type="submit" style="float:right" class="btn btn-primary btn-rounded">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

xpos314.web/xpos314.web/Views/CategoryTry/Index.cshtml
@using xpos314.viewmodels;
@{
	ViewData["Title"] = "Category Try";
}

<div class="card">
    <div class="card-body">
        <h2 class="card-title text-center">@ViewData["Title"]</h2>
        <button class="btn btn-primary btn-rounded mb-2" style="float: right" id="btn_create">
            <i data-feather="plus" class="feather-icon"></i>
            Create
        </button>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col" class="text-center">ID</th>
                    <th scope="col" class="text-center">Name Category</th>
                    <th scope="col" class="text-center">Description</th>
                    <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (VMTblCategory item in Model)
                {
                    <tr>
                        <th scope="row" class="text-center">@item.Id</th>
                        <td>@item.NameCategory</td>
                        <td>@item.Description</td>

                        <td class="text-center">
                            <a class="btn btn-primary btn_edit btn-rounded" style="color:white" data-id="@item.Id">Edit</a>
                            <a class="btn btn-success btn_detail btn-rounded" style="color:white" data-id="@item.Id">Detail</a>
                            <a class="btn btn-danger btn_delete btn-rounded" style="color:white" data-id="@item.Id">Delete</a>
                        </td>

                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>



<script>
    $(document).ready(function () {
        $("#btn_create").click(function () {
            $(".modal-body").load("/CategoryTry/Create")
            $("#myModal").modal("show")           
        })

        $(".btn_edit").click(function(){
            var id = $(this).data("id")
            $(".modal-body").load("/CategoryTry/Edit?id="+id)
            $("#myModal").modal("show")
        })
        $(".btn_detail").click(function(){
            var id = $(this).data("id")
            $(".modal-body").load("/CategoryTry/Detail?id="+id)
            $("#myModal").modal("show")
        })
        $(".btn_delete").click(function () {
            var id = $(this).data("id")
            $(".modal-body").load("/CategoryTry/Delete?id=" + id)
            $("#myModal").modal("show")
        })
        $("btn_search").click(function(){
            //alert("oke")
            $("#form_search").submit()
        })
    })
</script>