xpos314.web/xpos314.web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CustomerController : Controller
    {
        private CustomerService customerService;
        private RoleService roleService;
        private int IdUser = 1;

        public CustomerController(CustomerService _customerService, RoleService _roleService)
        {
            this.customerService = _customerService;
            this.roleService = _roleService;
        }


        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<VMTblCustomer> data = await customerService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameCustomer.ToLower().Contains(searchString.ToLower())
                || a.RoleName.ToLower().Contains(searchString.ToLower())
                 ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameCustomer).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameCustomer).ToList();
                    break;
            }
            return View(PaginatedList<VMTblCustomer>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMTblCustomer data = new VMTblCustomer();
            List<TblRole> listRole = await roleService.GetAllData();
            ViewBag.ListRole = listRole;
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblCustomer dataParam)
        {
            VMResponse response = await customerService.Create(dataParam);
            if (response.Success)
            {
                return Json(new { dataRespon = response });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Detail (int id)
        {
            VMTblCustomer data = await customerService.GetDataByIdCustomer(id);
            return PartialView(data);
        }

		public async Task<IActionResult> Delete(int id)
		{
			VMTblCustomer data = await customerService.GetDataByIdCustomer(id);
			return PartialView(data);
		}

		public async Task<IActionResult> SureDelete(int id)
		{
			VMResponse respon = await customerService.Delete(id);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}
			else
				return RedirectToAction("Index", id);
		}

        public async Task<IActionResult> Edit(int id)
        {
            VMTblCustomer data = await customerService.GetDataByIdCustomer(id);
            List<TblRole> listRole = await roleService.GetAllData();
            ViewBag.ListRole = listRole;
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblCustomer dataParam)
        {
            VMResponse respon = await customerService.Edit(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
    }
}

xpos314.web/xpos314.web/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class VariantController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private int IdUser = 1;

        public VariantController(CategoryService _categoryService, VariantService _varianService)
        {
            this.categoryService = _categoryService;
            this.variantService = _varianService;
        }

        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<VMTblVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                || a.Description.ToLower().Contains(searchString.ToLower()) 
                || a.NameCategory.ToLower().Contains(searchString.ToLower())
                 ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }
            return View(PaginatedList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

		public async Task<IActionResult> Create()
		{
			VMTblVariant data = new VMTblVariant();
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Create(VMTblVariant dataParam)
		{
			VMResponse respon = await variantService.Create(dataParam);
			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}


        public async Task<IActionResult> Edit(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Edit(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

		public async Task<IActionResult> Delete(int id)
		{
			VMTblVariant data = await variantService.GetDataById(id);
			return PartialView(data);
		}

		public async Task<IActionResult> SureDelete(int id)
		{
			VMResponse respon = await variantService.Delete(id);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}
			else
				return RedirectToAction("Index", id);
		}

        public async Task<IActionResult> Detail(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }
    }
}

xpos314.web/xpos314.web/Views/Customer/Create.cshtml
@using xpos314.viewmodels
@model VMTblCustomer
@{

	ViewData["Title"] = "Create Customer";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
		<form asp-action="Create" method="post" id="form_input">
			<div class="mb-4 row">
				<label for="NameCustomer" class="col-sm-6 col-form-label">Name Customer</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="NameCustomer" name="NameCustomer" value="@Model.NameCustomer">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="IdRole" class="col-sm-6 col-form-label">Role Name</label>
				<div class="col-sm-6">
					@Html.DropDownList("IdRole",
					new SelectList(ViewBag.ListRole, "Id", "RoleName"),
					"-- Choose Role --",
					new { @class="form-control" }
					)
				</div>
			</div>


			<div class="mb-4 row">
				<label for="Email" class="col-sm-6 col-form-label">Email</label>
				<div class="col-sm-6">
					<input type="email" class="form-control" id="Email" name="Email" value="@Model.Email">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Password" class="col-sm-6 col-form-label">Password</label>
				<div class="col-sm-6">
					<input type="password" class="form-control" id="Password" name="Password" value="@Model.Password">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Address" class="col-sm-6 col-form-label">Address</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="Address" name="Address" value="@Model.Address">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Phone" class="col-sm-6 col-form-label">Phone</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone">
				</div>
			</div>

			<div class="modal-footer">
				<div class="col-sm-12">
					<a class="btn btn-outline-secondary btn-rounded" asp-controller="Variant" asp-action="Index">Back to List</a>
					<button type="submit" style="float:right" class="btn btn-primary btn-rounded">Submit</button>
				</div>
			</div>
		</form>

	</div>
</div>

<script>
	$("#form_input").validate({
		errorClass: "text-danger",
		rules: {
			NameCustomer: {
				required: true,
				minlength: 5,
			},
			Phone: {
				required: true,
				number: true,
				minlength: 12,
				maxlength: 13
			},
			Password: {
				required: true,
				minlength: 6
			},
			Address: "required",
			Email: "required",
			IdRole: "required"
		},
		messages: {
			NameCutomer: {
				required: "Please fill name Customer!",
				minlength: "The Name must consist of at least 5 character!"
			},
			Phone: {
				required: "Please fill phone number!",
				number: "Please fill number only!",
				minlength: "The Number must consist of at least 12 digits!",
				maxlength: "The Number must consist of a maximum 13 digits!"
			},
			Password: {
				required: "Please fill password",
				minlength: "The Name must consist of at least 6 character!"
			},
			Address: "Please fill address",
			Email: "Please fill e-mail",
			IdRole: "Choose Your Role"
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize();
			$.ajax({
				url: "/Customer/Create",
				type: "POST",
				dataType: "json",
				data: dataForm,
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$(".modal").modal("hide")
						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					}
					else
						toastr.error(data.message)
				}
			})
		}
	})

</script>

xpos314.web/xpos314.web/Views/Customer/Delete.cshtml
@using xpos314.viewmodels
@model VMTblCustomer
@{
    ViewData["Title"] = "Delete Customer";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h3>Are you sure for delete @Model.NameCustomer?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary btn-rounded">Delete</button>
                <a asp-action="Index" class="btn btn-outline-secondary btn-rounded">Back to List</a>
            </div>
        </form>

    </div>
</div>

xpos314.web/xpos314.web/Views/Customer/Detail.cshtml
@using xpos314.viewmodels
@model VMTblCustomer
@{

	ViewData["Title"] = "Detail Customer";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
			<div class="mb-4 row">
				<label for="NameCustomer" class="col-sm-6 col-form-label">Name Customer</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="NameCustomer" name="NameCustomer" value="@Model.NameCustomer" readonly>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="RoleName" class="col-sm-6 col-form-label">Role Name</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="RoleName" name="RoleName" value="@Model.RoleName" readonly>
				</div>
			</div>

			<div class="mb-4 row">
				<label for="Email" class="col-sm-6 col-form-label">Email</label>
				<div class="col-sm-6">
					<input type="email" class="form-control" id="Email" name="Email" value="@Model.Email" readonly>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Address" class="col-sm-6 col-form-label">Address</label>
				<div class="col-sm-6">
				<textarea type="text" class="form-control" id="Address" name="Address" readonly>@Model.Address</textarea>
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Phone" class="col-sm-6 col-form-label">Phone</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone" readonly>
				</div>
			</div>
	</div>
</div>

xpos314.web/xpos314.web/Views/Customer/Edit.cshtml
@using xpos314.viewmodels
@model VMTblCustomer
@{

	ViewData["Title"] = "Edit Customer";
}

<div class="card">
	<div class="card-body">
		<div class="card-title">@ViewData["Title"]</div>
		<form asp-action="Create" method="post" id="form_input">
			<input type="hidden" id="Id" name="Id" value="@Model.Id" />
			<div class="mb-4 row">
				<label for="NameCustomer" class="col-sm-6 col-form-label">Name Customer</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="NameCustomer" name="NameCustomer" value="@Model.NameCustomer">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="IdRole" class="col-sm-6 col-form-label">Role Name</label>
				<div class="col-sm-6">
					@Html.DropDownList("IdRole",
					new SelectList(ViewBag.ListRole, "Id", "RoleName"),
					"-- Choose Role --",
					new { @class="form-control" }
					)
				</div>
			</div>


			<div class="mb-4 row">
				<label for="Email" class="col-sm-6 col-form-label">Email</label>
				<div class="col-sm-6">
					<input type="email" class="form-control" id="Email" name="Email" value="@Model.Email">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Password" class="col-sm-6 col-form-label">Password</label>
				<div class="col-sm-6">
					<input type="password" class="form-control" id="Password" name="Password" value="@Model.Password">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Address" class="col-sm-6 col-form-label">Address</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="Address" name="Address" value="@Model.Address">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="Phone" class="col-sm-6 col-form-label">Phone</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone">
				</div>
			</div>

			<div class="modal-footer">
				<div class="col-sm-12">
					<a class="btn btn-outline-secondary btn-rounded" asp-controller="Variant" asp-action="Index">Back to List</a>
					<button type="submit" style="float:right" class="btn btn-primary btn-rounded">Submit</button>
				</div>
			</div>
		</form>

	</div>
</div>

<script>
	$("#form_input").validate({
		errorClass: "text-danger",
		rules: {
			NameCustomer: {
				required: true,
				minlength: 5,
			},
			Phone: {
				required: true,
				number: true,
				minlength: 12,
				maxlength: 13
			},
			Password: {
				required: true,
				minlength: 6
			},
			Address: "required",
			Email: "required",
			IdRole: "required"
		},
		messages: {
			NameCutomer: {
				required: "Please fill name Customer!",
				minlength: "The Name must consist of at least 5 character!"
			},
			Phone: {
				required: "Please fill phone number!",
				number: "Please fill number only!",
				minlength: "The Number must consist of at least 12 digits!",
				maxlength: "The Number must consist of a maximum 13 digits!"
			},
			Password: {
				required: "Please fill password",
				minlength: "The Name must consist of at least 6 character!"
			},
			Address: "Please fill address",
			Email: "Please fill e-mail",
			IdRole: "Choose Your Role"
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize();
			$.ajax({
				url: "/Customer/Edit",
				type: "POST",
				dataType: "json",
				data: dataForm,
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$(".modal").modal("hide")
						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					}
					else
						toastr.error(data.message)
				}
			})
		}
	})

</script>

xpos314.web/xpos314.web/Views/Customer/Index.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model PaginatedList<VMTblCustomer>
@using System.Globalization;

@{
	ViewData["Title"] = "Data Customer";
}

<div class="card">
	<div class="card-header">
		<h2 class="card-title text-center">@ViewData["Title"]</h2>
		<div class="row mb-3">
			<div class="col-12">
				<form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
					<div class="d-flex bd-highlight mb-3">
						<div class="mr-auto p-2 bd-highlight">
							<button type="button" class="btn btn-primary shadow btn-rounded" id="btn_create">
								<i data-feather="plus" class="feather-icon"></i>
								Create
							</button>
						</div>
						<div class="p-1 bd-highlight input-group-text shadow custom-radius bg-white border-0 mr-2">
							<i data-feather="search" class="feather-icon ml-2" style="cursor:pointer" id="btn_search"></i>
							<input type="text" class="form-control custom-radius border-0" id="searchString" name="searchString" value="@ViewBag.currentFilter" placeholder="Search" />
						</div>
						<div class="p-2 bd-highlight shadow custom-radius border-0" style="cursor:pointer">
							<a class="input-group-text custom-radius border-0 bg-transparent  btn_reset" asp-action="Index">
								<i data-feather="refresh-cw" class="feather-icon "></i>
							</a>
						</div>

					</div>
				</form>
			</div>
		</div>


		<div class="card-body table-responsive p-0">
			<table class="table table-hover mb-3">
				<thead>
					<tr>
						<th class="text-center">Create Date</th>
						<th class="text-center">
							<a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
								<i class="fas fa-sort"></i>
								Name Customer
							</a>
						</th><th class="text-center">
							<a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
								<i class="fas fa-sort"></i>
								Role Name
							</a>
						</th>
						<th class="text-center">Email</th>
						<th class="text-center">Address</th>
						<th class="text-center">Phone</th>
						<th class="text-center">Action</th>
					</tr>
				</thead>
				<tbody>
					@if (Model.Count != 0)
					{
						@foreach (var item in Model)
						{
							<tr>
								<td class="text-center">@item.CreateDate.ToString("dd MMMM yyyy",new CultureInfo("id-ID"))</td>
								<td class="text-center">@item.NameCustomer</td>
								<td class="text-center">@item.RoleName</td>
								<td class="text-center">@item.Email</td>
								<td class="text-center">@item.Address</td>
								<td class="text-center">@item.Phone</td>
								<td class="text-center">
									<a class="btn btn-warning btn-rounded btn_detail" style="color:white" dataid="@item.Id">Detail</a>
									<a class="btn btn-success btn-rounded btn_edit" style="color:white" dataid="@item.Id">Edit</a>
									<a class="btn btn-danger btn-rounded btn_delete" style="color:white" dataid="@item.Id">Delete</a>
								</td>
							</tr>
						}
					}
					else
					{
						<tr>
							<td class="text-center" colspan="8">
								<i>Data not found</i>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>

		<div class="card-footer">
			@{
				var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
				var nextDisabled = !Model.HasNextPage ? "disabled" : "";
			}
			<div class="row">
				<div class="col-sm-12">
					<div class="d-flex justify-content-between">
						<div class="btn-group">
							<div class="mr-2">
								Show
							</div>
							<form asp-action="Index" id="form_pagesize">
								<select name="PageSize" id="PageSize" aria-controls="zero_config" class="form-control form-control-sm w-auto">
									<option value="3">3</option>
									<option value="5">5</option>
									<option value="10">10</option>
								</select>
							</form>
							<div class="ml-2"> entries from @Model.TotalData data</div>
							<input type="hidden" name="sortOrder" id="sort_change" value="" />
						</div>

						<div class="w-30">
							Page @Model.PageIndex of @Model.TotalPages
							<a asp-action="Index"
							   asp-route-sortOrder="@ViewBag.CurrentSort"
							   asp-route-pageNumber="@(Model.PageIndex - 1)"
							   asp-route-currentFilter="@ViewBag.CurrentFilter"
							   asp-route-pageSize="@ViewBag.CurrentPageSize"
		  class="btn btn-info  @prevDisabled">
								Previous
							</a>
							<a asp-action="Index"
							   asp-route-sortOrder="@ViewBag.CurrentSort"
							   asp-route-pageNumber="@(Model.PageIndex + 1)"
							   asp-route-currentFilter="@ViewBag.CurrentFilter"
							   asp-route-pageSize="@ViewBag.CurrentPageSize"
		  class="btn btn-info  @nextDisabled">
								Next
							</a>
						</div>
					</div>
				</div>



			</div>
		</div>
	</div>
</div>


<script>
	$(document).ready(function () {
		$("#btn_create").click(function () {
			$(".modal-body").empty();
			$(".modal-body").load("/Customer/Create")
			$("#myModal").modal("show");
		});

		$(".btn_detail").click(function () {
			var id = $(this).attr("dataid")
			$(".modal-body").empty();
			$(".modal-body").load("/Customer/Detail?id=" + id)
			$("#myModal").modal("show");
		});

		$(".btn_edit").click(function () {
			var id = $(this).attr("dataid")
			$(".modal-body").empty();
			$(".modal-body").load("/Customer/Edit?id=" + id)
			$("#myModal").modal("show");
		});

		$(".btn_delete").click(function () {
			var id = $(this).attr("dataid");
			$(".modal-body").empty();
			$(".modal-body").load("/Customer/Delete?id=" + id)
			$("#myModal").modal("show");
		});

		$("#PageSize").val(@ViewBag.CurrentPageSize)

		$("#PageSize").change(function () {
			$("#form_pagesize").submit();
		})

	});
</script>