xpos314.web/xpos314.web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
	public class AuthController : Controller
	{
		private AuthService authService;
		VMResponse response = new VMResponse();

		public AuthController(AuthService _authService)
		{
			this.authService = _authService;
		}
		public IActionResult Login()
		{
			return PartialView();
		}
		
		public IActionResult Logout()
		{
			HttpContext.Session.Clear();
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public async Task<JsonResult> LoginSubmit(string email, string password)
		{
			VMTblCustomer customer = await authService.CheckLogin(email, password);
			if (customer != null)
			{
				response.Message = $"Hello, {customer.NameCustomer} Welcome to XPOS";
				HttpContext.Session.SetString("NameCustomer", customer.NameCustomer);
				HttpContext.Session.SetInt32("IdCustomer", customer.Id);
				HttpContext.Session.SetInt32("IdRole", customer.IdRole ?? 0);

			}
			else
			{
				response.Success = false;
				response.Message = $"Oops, {email} not found or password is wrong, please check it!";
			}

			return Json(new { dataRespon = response });
		}

		public IActionResult Register()
		{
			return PartialView();
		}

		[HttpPost]
		public async Task<JsonResult> Register(TblCustomer customer)
		{
			response = await authService.CreateCustomer(customer);
			return Json(new {dataRespon = response});
		}

		public async Task<JsonResult> CheckEmailExisting(string email)
		{
			bool isExist = await authService.CheckEmailExisting(email);
			return Json(isExist);
		}
	}
}

xpos314.web/xpos314.web/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.web.Models;

namespace xpos314.web.Controllers
{
    public class FriendController : Controller
    {
        private static List<Friend> listFriends = new List<Friend> 
        { 
            new Friend(){Id=1, Name="Firdha", address="Tangerang Selatan"},
            new Friend(){Id=2, Name="Anwar", address="Ragunan"},                
        };
        public IActionResult Index()
        {

           ViewBag.Friends = listFriends;
            return View(listFriends);
        }

        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Friend friend)
        {
            listFriends.Add(friend);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Friend friend = listFriends.Find(i => i.Id == id)!;
            return View(friend);
        }

        [HttpPost]
        public IActionResult Edit(Friend friend)
        {
            Friend editfriend = listFriends.Find(i => i.Id == friend.Id)!;
            int indeks = listFriends.IndexOf(editfriend);
            if(indeks > -1)
            {
                listFriends[indeks].Id = friend.Id;
                listFriends[indeks].Name = friend.Name;
                listFriends[indeks].address = friend.address;
            }
            return RedirectToAction("Index");
        }

        public IActionResult Detail(int id)
        {
            Friend friend = listFriends.Find(i => i.Id == id)!;
            return View(friend);
        }

        /*public IActionResult Delete(int id)
        {
            Friend friend = listFriends.Find(i => i.Id == id)!;
            return View(friend);
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            Friend deletefriend = listFriends.Find(i => i.Id == int.Parse(id))!;
            listFriends.Remove(deletefriend);
            return RedirectToAction("index");
        }*/

        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Friend deleteFriend = listFriends.Find(i => i.Id == id)!;
            if (HttpContext.Request.Method == "POST")
            {
                listFriends.Remove(deleteFriend);
                return RedirectToAction("Index");
            }
            else
                return View(deleteFriend);
        }
    }
}

xpos314.web/xpos314.web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class OrderController : Controller
    {
        private ProductService productService;
        private OrderService orderService;
        private int IdUser = 1;

        public OrderController(ProductService _productService, OrderService _orderService)
        {
            this.productService = _productService;
            this.orderService = _orderService;
        }
        public async Task<IActionResult> Catalog(VMSearchPage dataSearch)
        {
            List<VMTblProduct> dataProduct = await productService.GetAllData();
            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;

            if (dataSearch.NameProduct != null)
                dataProduct = dataProduct.Where(a => a.NameProduct == dataSearch.NameProduct).ToList();

            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
                dataProduct = dataProduct.Where(a => a.Price >= dataSearch.MinAmount && a.Price < dataSearch.MaxAmount).ToList();

            //Set Session in VMTblOrderHeader first load
            VMTblOrderHeader dataHeader = HttpContext.Session.GetComplexData<VMTblOrderHeader>("ListCart");
            if (dataHeader == null)
            {
                dataHeader = new VMTblOrderHeader();
                dataHeader.ListDetails = new List<VMTblOrderDetail>();
            }
            var ListDetail = JsonConvert.SerializeObject(dataHeader.ListDetails);
            ViewBag.dataHeader = dataHeader;
            ViewBag.dataDetail = ListDetail;
            //End set session

            ViewBag.Search = dataSearch;
            ViewBag.CurrentPageSize = dataSearch.pageSize;


            return View(PaginatedList<VMTblProduct>.CreateAsync(dataProduct, dataSearch.pageNumber ?? 1, dataSearch.pageSize ?? 3));

        }

        //Set session in VMTblOrderHeader every add or minus
        [HttpPost]
        public JsonResult SetSession(VMTblOrderHeader dataHeader)
        {
            HttpContext.Session.SetComplexdata("ListCart", dataHeader);
            return Json("");
        }
        //END

        public JsonResult RefreshSession()
        {
            HttpContext.Session.Remove("ListCart");
            return Json("");
        }

        public IActionResult OrderPreview(VMTblOrderHeader dataHeader)
        {
            return PartialView(dataHeader);
        }

        public IActionResult SearchMenu()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> SubmitOrder(VMTblOrderHeader dataHeader)
        {
            //int IdCustomer = HttpContext.Session.GetInt32("IdCustomer") ?? 0;
            //dataHeader.IdCustomer = IdCustomer;
            dataHeader.IdCustomer = IdUser;          

            VMResponse response = await orderService.SubmitOrder(dataHeader);
            return Json(response);
        }

        public async Task<IActionResult> HistoryOrder(VMSearchPage dataSearch)
        {
            //int IdCustomer = HttpContext.Session.GetInt32("IdCustomer") ?? 0;
            int IdCustomer = IdUser;
            List<VMTblOrderHeader> data = await orderService.ListHeaderDetails(IdCustomer);
            int count = await orderService.CountTransaction(IdCustomer);
            ViewBag.Count = count;
            
            dataSearch.MinDate = dataSearch.MinDate == null ? DateTime.MinValue : dataSearch.MinDate;
            dataSearch.MaxDate = dataSearch.MaxDate == null ? DateTime.MaxValue : dataSearch.MaxDate;

            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;

            if (!string.IsNullOrEmpty(dataSearch.CodeTransaction))
            {
                data = data.Where(a => a.CodeTransaction.ToLower().Contains(dataSearch.CodeTransaction.ToLower())).ToList();
            }

            if(dataSearch.MinDate != null && dataSearch.MaxDate != null)
            {
                data = data.Where(a => a.CreateDate >= dataSearch.MinDate &&
                                        a.CreateDate <= dataSearch.MaxDate).ToList();
            }

            if(dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                data = data.Where(a => a.Amount >= dataSearch.MinAmount &&
                                        a.Amount <= dataSearch.MaxAmount).ToList();
            }
            ViewBag.Search = dataSearch;
            return View(data);
        }

        public IActionResult Search()
        {
            return PartialView();
        }
    }
}

xpos314.web/xpos314.web/Controllers/RoleController.cs
    using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class RoleController : Controller
    {
        private RoleService roleService;
        private int IdUser = 1;

        public RoleController(RoleService _roleService)
        {
            this.roleService = _roleService;
        }

        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<TblRole> data = await roleService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.RoleName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
				default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginatedList<TblRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));

        }
        public IActionResult Create()
        {
            TblRole data = new TblRole();
            return PartialView(data);
        }

		[HttpPost]
		public async Task<IActionResult> Create(TblRole dataParam)
		{
			dataParam.CreatedBy = IdUser;
			VMResponse respon = await roleService.Create(dataParam);
			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);


		}

		public async Task<JsonResult> CheckNameIsExist(string nameRole)
		{
			bool isExist = await roleService.CheckRoleName(nameRole);
			return Json(isExist);

		}

		public async Task<IActionResult> Detail(int id)
		{
			TblRole data = await roleService.GetDataById(id);
			return PartialView(data);
		}

		public async Task<IActionResult> Edit(int id)
		{
			TblRole data = await roleService.GetDataById(id);
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(TblRole dataParam)
		{
			dataParam.UpdatedBy = IdUser;
			VMResponse respon = await roleService.Edit(dataParam);
			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}

		public async Task<IActionResult> Delete(int id)
		{
			TblRole data = await roleService.GetDataById(id);
			return PartialView(data);
		}

		public async Task<IActionResult> SureDelete(int id)
		{
			int createBy = IdUser;
			VMResponse respon = await roleService.Delete(id, createBy);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}
			else
				return RedirectToAction("Index", id);
		}




	}
}

xpos314.web/xpos314.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xpos314.web</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/adminmart/assets/images/favicon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <!-- All Jquery -->
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="~/adminmart/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
   
    <!-- Custom CSS -->
    <link href="~/adminmart/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/adminmart/dist/css/style.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" type="text/css"/>

    <style>
        .field_icon {
            float: right;
            margin-left: -25px;
            margin-right: 5px;
            margin-top: -25px;
            position: relative;
            z-index: 2;
            color: lightgrey;
        }
    </style>

</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">

         <partial name="_Header" />
         <partial name="_Sidebar"/>

        <div class="page-wrapper">
            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="footer text-center text-muted">
                All Rights Reserved by Adminmart. Designed and Developed by <a href="https://wrappixel.com">WrapPixel</a>.
            </footer>
        </div>

    </div>





    <!-- ============================================================== -->
    <!-- Modal 1 -->
    <!-- ============================================================== -->
    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Modal 2-->
    <!-- ============================================================== -->
    <div class="modal fade" id="modal_sm" tabindex="-1"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-body" id="modal_body_sm">
                    ...
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!--Modal Large-->
    <!-- ============================================================== -->
    <div class="modal fade" id="modal_lg">
        <div class="modal-dialog modal-dialog-scrollable modal-lg">
            <div class="modal-content">
                <div class="modal-body" id="modal_body_lg">
                    ...
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    @*spinner*@
    <!-- ============================================================== -->
    <div class="modal fade" id="modal_load">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center" id="modal_load_body">
                    <div class="spinner-grow text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <h3>Please wait..</h3>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
 
    <script src="~/adminmart/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/adminmart/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/adminmart/dist/js/app-style-switcher.js"></script>
    <script src="~/adminmart/dist/js/feather.min.js"></script>
    <script src="~/adminmart/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/adminmart/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/adminmart/dist/js/custom.min.js"></script>
    <!--This page JavaScript -->
    <script src="~/adminmart/assets/extra-libs/c3/d3.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/c3/c3.min.js"></script>
    <script src="~/adminmart/assets/libs/chartist/dist/chartist.min.js"></script>
    <script src="~/adminmart/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/adminmart/dist/js/pages/dashboards/dashboard1.min.js"></script>
</body>
</html>

xpos314.web/xpos314.web/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xpos314.web</title>

    @*jquery*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*icon*@
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon.png">
    <title>Adminmart Template - The Ultimate Multipurpose admin template</title>
    <!-- Custom CSS -->
    <link href="assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="dist/css/style.min.css" rel="stylesheet">
    
</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <!-- Modal -->
    <div  class="modal fade " id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content ">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    
                </div>
                @*<div class="modal-footer">
                    <a class="btn btn-outline-secondary" asp-controller="categorytry" asp-action="index">back to list</a>
                    <button type="submit" style="float:right" class="btn btn-primary">submit</button>
                </div>*@
            </div>
        </div>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

xpos314.web/xpos314.web/Views/Shared/_Sidebar.cshtml
@using xpos314.web.Services

@inject AuthService authService
@{
	int IdCustomer = @Context.Session.GetInt32("IdCustomer") ?? 0;
	int IdRole = @Context.Session.GetInt32("IdRole") ?? 0;
	//string NameCustomer = @Context.Session.GetString("NameCustomer") ?? "";
	var menus = await authService.MenuAccess(IdRole);
}

<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">

	@if (IdCustomer != 0)
	{
		<!-- Sidebar scroll-->
		<div class="scroll-sidebar" data-sidebarbg="skin6">

			<nav class="sidebar-nav">
				<ul id="sidebarnav">
					@foreach (var parent in menus)
					{
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="@parent.MenuController" asp-action="@parent.MenuAction"
		aria-expanded="false">
								<i data-feather="@parent.MenuIcon" class="feather-icon "></i><span class="hide-menu">@parent.MenuName</span>
							</a>
						</li>

					}

					<li class="list-divider"></li>
					<li class="sidebar-item">
						<a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout" aria-expanded="false">
							<i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
						</a>
					</li>

				</ul>
			</nav>
			<!-- Sidebar navigation-->
			<!-- End Sidebar navigation -->
		</div>

		<!-- End Sidebar scroll-->



		@*<!-- Sidebar scroll-->
	<div class="scroll-sidebar" data-sidebarbg="skin6">
	@foreach (var parent in menus)
	{
	<nav class="sidebar-nav">
	<ul id="sidebarnav">
	<li class="sidebar-item">
	<a class="sidebar-link sidebar-link" asp-controller="@parent.MenuController" asp-action="@parent.MenuAction"
	aria-expanded="false">
	<i data-feather="@parent.MenuIcon" class="feather-icon "></i><span class="hide-menu">@parent.MenuName</span>
	</a>
	</li>

	</ul>
	</nav>
	}
	<!-- Sidebar navigation-->

	<!-- End Sidebar navigation -->
	</div>*@
		<!-- End Sidebar scroll-->
		<!-- Sidebar Menu -->
		@*<nav class="mt-2">
	<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
	<!-- Add icons to the links using the .nav-icon class
	with font-awesome or any other icon font library -->
	@foreach (var parent in menus)
	{
	<li class="nav-item menu-open">
	<a href="#" class="nav-link">
	<i class="nav-icon @parent.MenuIcon"></i>
	<p>
	@parent.MenuName
	<i class="right fas fa-angle-left"></i>
	</p>
	</a>
	<ul class="nav nav-treeview">

	@foreach (var child in parent.ListChild)
	{
	<li class="nav-item">
	<a asp-controller="@child.MenuController" asp-action="@child.MenuAction" class="nav-link">
	<i class="@child.MenuIcon nav-icon"></i>
	<p>@child.MenuName</p>
	</a>
	</li>
	}
	</ul>
	</li>
	}

	</ul>
	</nav>*@
		<!-- /.sidebar-menu -->
		@*@{
		if (IdCustomer != 0)
		{
			<!-- Sidebar scroll-->
			<div class="scroll-sidebar" data-sidebarbg="skin6">
				<!-- Sidebar navigation-->
				<nav class="sidebar-nav">
					<ul id="sidebarnav">
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" href="index.html"
							   aria-expanded="false">
								<i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
							</a>
						</li>
						<li class="list-divider"></li>
						<li class="nav-small-cap"><span class="hide-menu">Master</span></li>

						<li class="sidebar-item">
							<a class="sidebar-link" asp-controller="Friend" asp-action="Index"
			aria-expanded="false">
								<i data-feather="users" class="feather-icon"></i><span class="hide-menu">
									Friend
								</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="CategoryTry" asp-action="Index"
			aria-expanded="false">
								<i data-feather="clipboard" class="feather-icon"></i>
								<span class="hide-menu">Category Try</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="VariantTry" asp-action="Index"
			aria-expanded="false">
								<i data-feather="clipboard" class="feather-icon"></i>
								<span class="hide-menu">Variant Try</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="Category" asp-action="Index"
			aria-expanded="false">
								<i data-feather="clipboard" class="feather-icon"></i>
								<span class="hide-menu">Category</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="Variant" asp-action="Index"
			aria-expanded="false">
								<i data-feather="clipboard" class="feather-icon"></i>
								<span class="hide-menu">Variant</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="Product" asp-action="Index"
			aria-expanded="false">
								<i data-feather="clipboard" class="feather-icon"></i>
								<span class="hide-menu">Product</span>
							</a>
						</li>


						<li class="list-divider"></li>
						<li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>

						<li class="sidebar-item">
							<a class="sidebar-link" asp-controller="Order" asp-action="Catalog"
			aria-expanded="false">
								<i data-feather="book-open" class="feather-icon"></i>
								<span class="hide-menu">Menu Catalog</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="Order" asp-action="HistoryOrder"
			aria-expanded="false">
								<i data-feather="clipboard" class="feather-icon"></i>
								<span class="hide-menu">History Order</span>
							</a>
						</li>

						<li class="list-divider"></li>
						<li class="nav-small-cap"><span class="hide-menu">Configuration</span></li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="Role" asp-action="Index"
			aria-expanded="false">
								<i data-feather="clipboard" class="feather-icon"></i>
								<span class="hide-menu">Role</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="Customer" asp-action="Index"
			aria-expanded="false">
								<i data-feather="clipboard" class="feather-icon"></i>
								<span class="hide-menu">Customer</span>
							</a>
						</li>

						<li class="list-divider"></li>
						<li class="sidebar-item">
							<a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout"
			aria-expanded="false">
								<i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
							</a>
						</li>
					</ul>
				</nav>
				<!-- End Sidebar navigation -->
			</div>
			<!-- End Sidebar scroll-->
		}
	}*@
	}
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->